WILL-2132/Redirect-modul
BenjaminMedia/willow-base-theme pull request #485
Opened 2021-06-14 08:14 UTC by petruIPGroup2021

WILL-2132/Redirect-modul

2021-06-14 08:33 UTC, SorenThorup requested changes

2021-06-14 08:33 UTC, SorenThorup commented on functions.php
> +function try_redirect_url() {
Why are we doing this in functions.php?
If anything should be fixed like this, it should be done in our redirect plugin... 😃

2021-06-14 09:00 UTC, petruIPGroup2021 commented on functions.php
> +function try_redirect_url() {
in functions.php was more simple ;), ok I will disabled all plugin and I will check with enabled redirect only, probably redirect plugin do conflict with another plugins

2021-07-30 14:04 UTC, mrhn commented
As i see it, this does not align with our redirect module. If this is a mistake please write to me

2021-07-30 14:04 UTC, closed without merging